name = "Lightly Fabric Modded"
author = "TheOtherAnxxity"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02f828b0a6d090704413b43e39850531a304dd7fa2d3e8638e6e9d964d3f1612"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
