name = "Lightly Fabric Modded"
author = "TheOtherAnxxity"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef25f06ed3f7ee4605d890b895ad183df08ad6d2933f71227450f66c82ebdc93"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
