name = "Lightly Fabric Modded"
author = "TheOtherAnxxity"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fea8c57f19ba3b8fe6d60edcae1b3d0f5927aa5fb2dcd99f9b3a1fe9c251b471"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
