name = "Lightly Fabric Modded"
author = "TheOtherAnxxity"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77ec68f7c30d43a91152ef66c77e45906de716c5dd9939ff001f394d60f5d599"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
