name = "Extra Origins"
filename = "extraorigins-1.16.5-11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3274/277/extraorigins-1.16.5-11.jar"
hash-format = "murmur2"
hash = "2796320318"

[update]
[update.curseforge]
file-id = 3274277
project-id = 398419
release-channel = "beta"
