name = "Terrestria"
filename = "terrestria-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3193/392/terrestria-2.2.0.jar"
hash-format = "murmur2"
hash = "1437369089"

[update]
[update.curseforge]
file-id = 3193392
project-id = 323974
release-channel = "beta"
