name = "Guns Go Brrrr"
author = "TheOtherAnxxity"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cee78b663c541b154b19eb79348534aa3804825928577de1c2dbebd70f0bcad2"

[versions]
forge = "36.1.0"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.5"]
